FROM nvidia/cuda:11.8-runtime-ubuntu22.04
RUN apt-get update && apt-get install -y python3 python3-pip libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY requirements.txt requirements-api.txt requirements-metrics.txt /app/
RUN pip3 install --no-cache-dir -r requirements.txt -r requirements-api.txt -r requirements-metrics.txt
COPY . /app
CMD ["python3", "main.py", "--sources", "0"]
